### PR TITLE
Added Russian translation

### PR DESCRIPTION
**Pull request by Blueberryy**

### CODE REVIEW

**Comment by MAGNAT2645** [comment]
No offense, but you have a lot of grammatical errors.
Also try to not combine "вы" with "ты", use only one pronoun.

**Comment by Blueberryy** [comment]
Alright, should i close my pull?

**Comment by Phil25** [comment]
You don't have to close it. If you know how, you can fix it up.

**Comment by Blueberryy** [comment]
Nah. If someone want to fix it then sure, you can use my translation as base.

**Pull request closed without merging**
